Feature/ui cleaning
chingu-voyages/v24-geckos-team-03 pull request #51
Opened 2020-11-07 01:23 UTC by Rayhan1998

1.Made Movie details page and home page responsive.
2. Will add left and right arrows for actors and trailers in next branch. Still trying to figure out the math behind it.

2020-11-08 03:21 UTC, dpajek requested changes
-I made some comments inline below. 
-Also, I noticed that the filter picks up some incorrect matches. For example, if I do science fictor + 2010, I get a bunch of movies (wall-e, terminator, the thing, back to the future 2 & 3, etc).
-There are two 2016s in the dropdown list.
-The dropdowns don't always match what's being searched.
--ex1, if I set the genre & year in the filter, click submit, then I click on a movie and go to the movie details 'page', then I hit that back arrow, the page title will be popular movies, the grid will show filter results, but the filters will be clear
--ex2, if I set the genre & year in the filter, click submit, then I click Daily Flix to go back to the homepage, it will show the popular movies title, the grid will show the popular movies, but the filter will show the genre & year that was selected earlier

-If I navigate to the moviedetails page from the searchbyactors, then I hit the back arrow, then it doesn't go back to searchbyactors

2020-11-08 03:21 UTC, dpajek commented on package.json
> +  "homepage": "http://localhost:3000/v24-geckos-team-03",
This will break deployment to GH Pages. What's the reason for changing this to localhost? Did it have a positive impact somewhere?

2020-11-08 03:21 UTC, dpajek commented on src/components/FilterBar/filter.css
> +}
chakra has a short-hand framework that let's you define responsive components without having to define media queries: https://chakra-ui.com/responsive-styles
Would it make sense that instead?

2020-11-08 03:30 UTC, Rayhan1998 commented on package.json
> +  "homepage": "http://localhost:3000/v24-geckos-team-03",
That was an error on my end. I will change it back to "homepage": "http://chingu-voyages.github.io/v24-geckos-team-03",

2020-11-08 03:30 UTC, Rayhan1998 commented on src/components/FilterBar/filter.css
> +}
I tried to use the filter from chakra but for some reason it didn't let me submit the inputs so I just sticked to html form element.

2020-11-08 03:30 UTC, Rayhan1998 commented
"-If I navigate to the moviedetails page from the searchbyactors, then I hit the back arrow, then it doesn't go back to searchbyactors"

I was assuming the default would be to go back to home page. But I will see if I can implement a if statement to determine if we go back to either home page or actors page.

2020-11-08 03:33 UTC, dpajek commented on src/components/FilterBar/filter.css
> +}
Works for me! 👍

2020-11-09 23:58 UTC, dpajek approved these changes
looks good! 👍

2020-11-09 23:58 UTC, merged